#!/usr/bin/env perl

# Copyright (c) 2011, Ryan M. Lefever
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are
# met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above
#       copyright notice, this list of conditions and the following
#       disclaimer in the documentation and/or other materials provided
#       with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
# "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
# LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
# A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
# HOLDER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
# SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
# LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
# DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
# THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# DESCRIPTION: This command combines find and grep to perform a
#              recursive grep in the current directory.

# enable perl's safety info
use strict;
use warnings;

use SiltCommon;

# globals
my $search = "";
my @ignoreDirs;
my @ignoreFileTypes;
my @fileExts;
my @files;
my $grep = "grep -H -n";

# Parse command line arguments
parsecla();

# Build find command
my $exclude = "";
my $dir;
my $f;
foreach $dir (@ignoreDirs){
  if($dir =~ /^\.\//){ $exclude = $exclude . " -type d -wholename " . $dir; }
  else{ $exclude = $exclude . " -type d -name " . $dir; }
  $exclude = $exclude . " -prune -o";
}
foreach $f (@ignoreFileTypes){
  $exclude = $exclude . " -type f -name \"*." . $f . "\" -prune -o";
}
my $cmd = "";
if($#fileExts == -1){
  $cmd = "find" . $exclude . " \\( -type f -print \\)";
}
else{
  $cmd = "find" . $exclude . " \\( -type f \\(";
  my $ext;
  my $j;
  for($j=0; $j <= $#fileExts; ++$j){
    if($j > 0){ $cmd = $cmd . " -o"; }
    $cmd = $cmd . " -name \"*." . $fileExts[$j] . "\"";
  }
  $cmd = $cmd . " \\) -print \\)";
}

# Run find command and store the results to @files
@files = split /\n/, SiltCommon::runcmd_backtics($cmd);
if(SiltCommon::verbose()){
  print "Will search these files ...\n";
  foreach $f (@files){
    print "  [" . $f . "]\n";
  }
}

# Grep the files in @files for $search
foreach $f (@files){
  SiltCommon::runcmd($grep . " '" . $search . "' " . $f);
}
exit(0);

# A function to parse command line arguments.
sub parsecla{
  my $arg;
  foreach $arg(@ARGV){
    if($arg eq "--help" || $arg eq "-h"){ usage(); exit(0); }
    elsif($arg eq "--verbose"){ SiltCommon::setverbose(1); }
    elsif($arg eq "--norun"){ SiltCommon::setnorun(1); }
    elsif($arg =~ /^--ignore-dir=(.+)/){ push(@ignoreDirs, (split /,/, $1)); }
    elsif($arg =~ /^--ignore-ft=(.+)/){
      push(@ignoreFileTypes, (split /,/, $1));
    }
    elsif($arg =~ /^--accept-ft=(.+)/){ push(@fileExts, (split /,/, $1)); }
    elsif($arg eq "--files-only"){ $grep = $grep . " -l"; }
    elsif($arg eq "--case-insensitive"){ $grep = $grep . " -i"; }
    elsif($arg eq "--regex"){ $grep = $grep . " -E"; }
    elsif($arg =~ /^-/){
      print "Illegal argument: " . $arg . "\n";
      usage();
      exit(1);
    }
    elsif($search eq ""){ $search = $arg; }
    else{ print "Too many positional arguments\n"; usage(); exit(1); }
  }

  if($search eq ""){ print "No search specified\n"; usage(); exit(1); }
}

# Print usage information for grep-recursive.
sub usage{
  print "USAGE: grep-recursive [OPTIONS] <search>
DESCRIPTION: Recursively grep for <search> in the current directory.
             This program is part of the SiLT project:
             http://code.google.com/p/silt
OPTIONS:
  --help,-h           print this message
  --accept-ft=<list>  only consider files with the listed extensions
  --case-insensitive  search is case insensitive
  --files-only        only list files with matches
  --ignore-dir=<list> ignore files in the specified list of directories; any
                      directory matching a name in the list will be ignored
                      unless the item starts './', in which case only a
                      directory with the full path will be ignored
  --ignore-ft=<list>  ignore files with the listed extensions
  --norun             do not run commands, most useful with --verbose
  --regex             treat search as a regular expression
  --verbose           enable verbose output
";
}
